title: Jason Deacutis - Portfolio
description: Game development and graphics programming work.
locale: en_US

owner:
  name: Jason Deacutis
  bio: Personal software/game development portfolio website.
  email: jasondeacutis@gmail.com
  linkedin: jasondeacutis
  github: https://github.com/JasonDeacutis
  google:
    plus: jasondeacutis

theme: jekyll-theme-primer
layout: default
plugins:
  - jekyll-feed