title: Jason Deacutis - Portfolio
locale: en_US

owner:
  name: Jason Deacutis
  bio: "Personal software/game development portfolio website."
  email: jasondeacutis@gmail.com
  linkedin: jasondeacutis
  github: waffle1434
  google:
    plus: jasondeacutis